dieasemain/views/yak_views.py
import requests
import xml.etree.ElementTree as ET
from flask import Blueprint, url_for, request, render_template, g
from flask import Blueprint, url_for, render_template, abort
from werkzeug.utils import redirect

bp = Blueprint('yak', __name__, url_prefix='/')
totalCount = 0


@bp.route('/yak', methods=['GET', 'POST'])
def list():
    if request.method == 'POST':
        # 검색 폼이 제출되었을 때의 처리
        search_query = request.form['search_query1']
        print(search_query, "=================================")

    else:
        data1 = []
        url = 'http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList'
        pageNo = int(request.args.get('page', 1))
        numOfRows = int(request.args.get('numOfRows', 10))  # 한 페이지에 보여질 항목 수
        params = {
            'serviceKey': 'VQjISU0hGRUuuYzKzUZimCJgNkWsFFAr0VpkfbEIVawBMPCw0FI9aXf0bJ2v1zuDQe45Kupb0ajUCJwjGNQ2cA==',
            'pageNo': pageNo, 'numOfRows': numOfRows, 'entpName': '', 'itemName': '', 'itemSeq': '', 'efcyQesitm': '',
            'useMethodQesitm': '', 'atpnWarnQesitm': '', 'atpnQesitm': '', 'intrcQesitm': '', 'seQesitm': '',
            'depositMethodQesitm': '', 'openDe': '', 'updateDe': '', 'type': 'xml'}
        response = requests.get(url, params=params)

        print(response.status_code)

        if response.status_code == 200:
            # XML 데이터를 파싱합니다
            root = ET.fromstring(response.content)

            try:
                for item in root.findall('.//item'):  # 'item' 태그를 가진 모든 요소를 찾습니다
                    entry = {
                        'itemName': item.find('itemName').text,
                        'itemSeq': item.find('itemSeq').text,  # 상세 정보를 위해 itemSeq를 저장
                        'entpName': item.find('entpName').text,
                        'efcyQesitm': item.find('efcyQesitm').text,
                        'useMethodQesitm': item.find('useMethodQesitm').text,
                        'atpnWarnQesitm': item.find('atpnWarnQesitm').text,
                        'atpnQesitm': item.find('atpnQesitm').text,
                        'intrcQesitm': item.find('intrcQesitm').text,
                        'seQesitm': item.find('seQesitm').text,
                        'depositMethodQesitm': item.find('depositMethodQesitm').text
                    }
                    data1.append(entry)
                totalCount = int(root.find('.//totalCount').text)
                for item in root.findall('.//response'):  # 'item' 태그를 가진 모든 요소를 찾습니다
                    entry1 = {
                        'pageNo': item.find('pageNo').text
                    }
                    data1.append(entry1)

            except ET.ParseError as e:
                print(f"XML 파싱 오류: {e}")
                data1 = []

            total_pages = (totalCount + numOfRows - 1) // numOfRows

    return render_template('yak/list.html', data=data1, totalCount=totalCount, total_pages=total_pages,
                           current_page=pageNo, numOfRows=numOfRows)


# 약품의 세부정보 확인
@bp.route('/yak/<int:itemSeq><itemName>')
def detail(itemSeq, itemName):
    data1 = []
    url = 'http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList'
    pageNo = int(request.args.get('page', 1))
    numOfRows = int(request.args.get('numOfRows', 10))  # 한 페이지에 보여질 항목 수
    params = {
        'serviceKey': 'VQjISU0hGRUuuYzKzUZimCJgNkWsFFAr0VpkfbEIVawBMPCw0FI9aXf0bJ2v1zuDQe45Kupb0ajUCJwjGNQ2cA==',
        'pageNo': pageNo, 'numOfRows': numOfRows, 'entpName': '', 'itemName': itemName, 'itemSeq': '', 'efcyQesitm': '',
        'useMethodQesitm': '', 'atpnWarnQesitm': '', 'atpnQesitm': '', 'intrcQesitm': '', 'seQesitm': '',
        'depositMethodQesitm': '', 'openDe': '', 'updateDe': '', 'type': 'xml'}
    response = requests.get(url, params=params)

    root = ET.fromstring(response.content)

    detail_data = {}
    item = root.find('.//item')
    if item is not None:
        detail_data = {
            'name': item.find('itemName').text,
            'entpName': item.find('entpName').text,
            'efcyQesitm': item.find('efcyQesitm').text,
            'useMethodQesitm': item.find('useMethodQesitm').text,
            'atpnWarnQesitm': item.find('atpnWarnQesitm').text,
            'atpnQesitm': item.find('atpnQesitm').text,
            'intrcQesitm': item.find('intrcQesitm').text,
            'seQesitm': item.find('seQesitm').text,
            'depositMethodQesitm': item.find('depositMethodQesitm').text,
            'itemImage': item.find('itemImage').text
        }
        data1.append(detail_data)
    else:
        print("아이템을 찾을 수 없습니다.")
        abort(404, description="Item not found.")

    return render_template('yak/detail.html', detail_data=detail_data)


# # 약품의 세부정보 확인
# @bp.route('/yak/search')
# def search():
#     detail_data = {}
#     data1 = []
#     # GET 요청으로 받은 검색어 처리
#     search_query = request.args.get('search_query1')
#     print(search_query)
#
#     pageNo = int(request.args.get('page', 1))
#     numOfRows = int(request.args.get('numOfRows', 100))  # 한 페이지에 보여질 항목 수
#     print(search_query)
#     efcyQesitm = search_query
#     # API를 호출하여 검색 결과를 가져옵니다.
#     # 가져온 결과를 템플릿에 전달하여 보여줍니다.
#     url = 'http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList'
#     pageNo = int(request.args.get('page', 1))
#     params = {
#         'serviceKey': 'VQjISU0hGRUuuYzKzUZimCJgNkWsFFAr0VpkfbEIVawBMPCw0FI9aXf0bJ2v1zuDQe45Kupb0ajUCJwjGNQ2cA==',
#         'pageNo': pageNo, 'numOfRows': numOfRows, 'entpName': '', 'itemName': '', 'itemSeq': '', 'efcyQesitm': efcyQesitm,
#         'useMethodQesitm': '', 'atpnWarnQesitm': '', 'atpnQesitm': '', 'intrcQesitm': '', 'seQesitm': '',
#         'depositMethodQesitm': '', 'openDe': '', 'updateDe': '', 'type': 'xml'}
#     response = requests.get(url, params=params)
#
#     root = ET.fromstring(response.content)
#
#     item = root.find('.//item')
#     if item is not None:
#         print(search_query, "=============================================================")
#         detail_data = {
#             'name': item.find('itemName').text,
#             'entpName': item.find('entpName').text,
#             'efcyQesitm': item.find('efcyQesitm').text,
#             'useMethodQesitm': item.find('useMethodQesitm').text,
#             'atpnWarnQesitm': item.find('atpnWarnQesitm').text,
#             'atpnQesitm': item.find('atpnQesitm').text,
#             'intrcQesitm': item.find('intrcQesitm').text,
#             'seQesitm': item.find('seQesitm').text,
#             'depositMethodQesitm': item.find('depositMethodQesitm').text,
#             'itemImage': item.find('itemImage').text
#         }
#         data1.append(detail_data)
#     else:
#         print("아이템을 찾을 수 없습니다.")
#         abort(404, description="Item not found.")
#
#     totalCount = int(root.find('.//totalCount').text)
#     for item in root.findall('.//response'):  # 'item' 태그를 가진 모든 요소를 찾습니다
#         entry1 = {
#             'pageNo': item.find('pageNo').text
#         }
#         data1.append(entry1)
#
#     data1 = []
#
#     total_pages = (totalCount + numOfRows - 1) // numOfRows
#
#     return render_template('yak/search_form.html', detail_data=detail_data,totalCount=totalCount, total_pages=total_pages,
#                            current_page=pageNo, numOfRows=numOfRows)
#


@bp.route('/yak/search')
def search():
    search_query = request.args.get('search_query1', '')
    pageNo = int(request.args.get('page', 1))
    numOfRows = int(request.args.get('numOfRows', 10))

    url = 'http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList'
    params = {
        'serviceKey': 'VQjISU0hGRUuuYzKzUZimCJgNkWsFFAr0VpkfbEIVawBMPCw0FI9aXf0bJ2v1zuDQe45Kupb0ajUCJwjGNQ2cA==',
        'pageNo': pageNo, 'numOfRows': numOfRows, 'entpName': '', 'itemName': '', 'itemSeq': '',
        'efcyQesitm': search_query,  # 검색어를 efcyQesitm에 포함
        'useMethodQesitm': '', 'atpnWarnQesitm': '', 'atpnQesitm': '', 'intrcQesitm': '', 'seQesitm': '',
        'depositMethodQesitm': '', 'openDe': '', 'updateDe': '', 'type': 'xml'}

    response = requests.get(url, params=params)

    data1 = []
    totalCount = 0
    total_pages = 0

    if response.status_code == 200:
        root = ET.fromstring(response.content)
        items = root.findall('.//item')

        if items:
            for item in items:
                efcyQesitm_text = item.find('efcyQesitm').text if item.find('efcyQesitm') is not None else ''
                if search_query in efcyQesitm_text:
                    detail_data = {
                        'name': item.find('itemName').text if item.find('itemName') is not None else 'N/A',
                        'entpName': item.find('entpName').text if item.find('entpName') is not None else 'N/A',
                        'efcyQesitm': item.find('efcyQesitm').text if item.find('efcyQesitm') is not None else 'N/A',
                        'useMethodQesitm': item.find('useMethodQesitm').text if item.find('useMethodQesitm') is not None else 'N/A',
                        'atpnWarnQesitm': item.find('atpnWarnQesitm').text if item.find('atpnWarnQesitm') is not None else 'N/A',
                        'itemImage': item.find('itemImage').text if item.find('itemImage') is not None else 'N/A'
                    }
                    data1.append(detail_data)

            totalCount = int(root.find('.//totalCount').text)
            total_pages = (totalCount + numOfRows - 1) // numOfRows
        else:
            abort(404, description="Item not found.")
    else:
        abort(response.status_code, description="API request failed.")

    return render_template('yak/search_form.html', search_query=search_query, data=data1, totalCount=totalCount, total_pages=total_pages,
                           current_page=pageNo, numOfRows=numOfRows)

dieasemain/templates/yak/detail.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="game_title">
        <strong>약품추천</strong>
        <p>호소하는 증상과 관련된 약을 알려줘요</p>
    </div>

    <div style="padding: 1%">
        <h1>제품명 : {{ detail_data['name'] }}</h1>
        <table style="width: 100%; padding: 5px;" class="table">
            <thead>
            <tr>
                <th>제조사</th>
                <th>효능효과</th>
                <th>사용방법</th>
                <th>주의사항 경고</th>
                <th>주의사항</th>
                <th>상호작용</th>
                <th>부작용</th>
                <th>보관방법</th>
                <th>제품 사진</th>
            </tr>
            </thead>
            <tbody>
            <tr>

                <td>제조사: {{ detail_data['entpName'] }}</td>
                <td>효능효과: {{ detail_data['efcyQesitm'] }}</td>
                <td>사용방법: {{ detail_data['useMethodQesitm'] }}</td>
                <td>주의사항 경고: {{ detail_data['atpnWarnQesitm'] }}</td>
                <td>주의사항: {{ detail_data['atpnQesitm'] }}</td>
                <td>상호작용: {{ detail_data['intrcQesitm'] }}</td>
                <td>부작용: {{ detail_data['seQesitm'] }}</td>
                <td>보관방법: {{ detail_data['depositMethodQesitm'] }}</td>
                <td>제품 사진:
                    <img src="{{ detail_data['itemImage'] or url_for('static', filename='default_image.png') }}"
                         width="200"
                         height="200"/>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
    {% endblock %}

dieasemain/templates/yak/list.html
{% extends "base.html" %}
{% block content %}

<div class="container my-3">
    <div class="game_title">
        <strong>약정보를 불러와요</strong>
        <p>호소하는 증상과 관련된 약을 알려줘요</p>
    </div>

    <form action="{{ url_for('yak.search') }}" method="GET">
        <div class="input-group mb-3">
            <input type="text" style="width: 50%; padding: 5px" placeholder="증상을 입력해요"  name="search_query1">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">검색</button>
            </div>
        </div>
    </form>
  <div style="background: #dddd">
    <table class="table">
        <tbody>
        {% if data %}
        <div>
            <p> 총 {{totalCount}} 개의 약 정보가 있습니다. </p>


            <form action="{{ url_for('yak.search') }}" method="GET">
                <p> 한번에 불러올 갯수를 선택하세요</p>
                <select id="numOfRows" name="numOfRows">
                    <option value="5" {% if numOfRows== 5 %}selected{% endif %}>5</option>
                    <option value="10" {% if numOfRows== 10 %}selected{% endif %}>10</option>
                    <option value="20" {% if numOfRows== 20 %}selected{% endif %}>20</option>
                    <option value="30" {% if numOfRows== 30 %}selected{% endif %}>30</option>
                    <script>
                        // 페이지당 항목 수를 변경할 때마다 페이지를 다시로드하여 URL에 변경된 값이 반영되도록 함
                        document.getElementById('numOfRows').addEventListener('change', function () {
                            var selectedNumOfRows = this.value;
                            var urlParams = new URLSearchParams(window.location.search);
                            urlParams.set('numOfRows', selectedNumOfRows);
                            window.location.href = window.location.pathname + '?' + urlParams.toString();
                        });
                    </script>
                </select>

            </form>
        </div>


        {% for item in data %}
        <a href="{{ url_for('yak.detail', itemSeq=item['itemSeq'], itemName=item['itemName']) }}">{{item.itemName}}</a>
        <p></p>
        <div></div>
        {% endfor %}

<!--        <p> 뭔가 불러왔습니다.</p>-->
        {% else %}
        <tr>
            <td colspan="3"> 약 정보가 없습니다...</td>
        </tr>
        {% endif %}

    </table>


    {% if current_page > 1 %}
    <a href="{{ url_for('yak.list', page=1) }}">처음</a>
    <a href="{{ url_for('yak.list', page=current_page - 1) }}">이전</a>
    {% endif %}

    {% if current_page < total_pages %}
    <a href="{{ url_for('yak.list', page=current_page + 1) }}">다음</a>
    <a href="{{ url_for('yak.list', page=total_pages) }}">마지막</a>
    {% endif %}


    //
    {% if data %}

    <div>
        {% set start_page = ((current_page - 1) // 10) * 10 + 1 %}
        {% set end_page = start_page + 9 %}
        {% if end_page > total_pages %}
        {% set end_page = total_pages %}
        {% endif %}

        {% if current_page > 10 %}
        <a href="{{ url_for('yak.list', page=start_page-10, search_query1=request.args.get('search_query1', ''), numOfRows=numOfRows) }}">이전</a>
        {% endif %}

        {% for page in range(start_page, end_page + 1) %}
        {% if page == current_page %}
        <strong>{{ page }}</strong>
        {% else %}
        <a href="{{ url_for('yak.list', page=page, search_query1=request.args.get('search_query1', ''), numOfRows=numOfRows) }}">{{
            page }}</a>
        {% endif %}
        {% endfor %}

        {% if end_page < total_pages %}
        <a href="{{ url_for('yak.list', page=start_page+10, search_query1=request.args.get('search_query1', ''), numOfRows=numOfRows) }}">다음</a>
        {% endif %}
    </div>
    {% else %}
    <p>검색 결과가 없습니다.</p>
    {% endif %}
    <p>페이지: {{ current_page }} / {{ total_pages }}</p>
</div>
</div>
{% endblock %}

dieasemain/templates/yak/search_form.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="game_title">
        <strong>약품추천</strong>
        <p>호소하는 증상과 관련된 약을 알려줘요</p>
    </div>
    <div style="width: 100%; padding: 1rem">
        <form method="get" action="{{ url_for('yak.search') }}">
            <input type="text" name="search_query1" placeholder="증상을 입력해봐요"
                   value="{{ request.args.get('search_query1', '') }}">
            <button type="submit">검색</button>
        </form>
        <form action="{{ url_for('yak.search') }}" method="GET">
            <p> 한번에 불러올 갯수를 선택하세요
                <select id="numOfRows" name="numOfRows">
                    <option value="5" {% if numOfRows== 5 %}selected{% endif %}>5</option>
                    <option value="10" {% if numOfRows== 10 %}selected{% endif %}>10</option>
                    <option value="20" {% if numOfRows== 20 %}selected{% endif %}>20</option>
                    <option value="30" {% if numOfRows== 30 %}selected{% endif %}>30</option>
                    <script>
                        // 페이지당 항목 수를 변경할 때마다 페이지를 다시로드하여 URL에 변경된 값이 반영되도록 함
                        document.getElementById('numOfRows').addEventListener('change', function() {
                            var selectedNumOfRows = this.value;
                            var urlParams = new URLSearchParams(window.location.search);
                            urlParams.set('numOfRows', selectedNumOfRows);
                            window.location.href = window.location.pathname + '?' + urlParams.toString();
                        });
                    </script>
                </select>
            </p>

        </form>
        {% for item in detail_data %}

        <h1>제품명 : {{ detail_data['name'] }}</h1>

        {% endfor %}

        {% if data %}
        <p>총 {{ totalCount }} 개의 약 정보가 있습니다.</p>

        <table class="table">
            <thead>
            <tr>
                <th>제품명</th>
                <th>제조사</th>
                <th>효능효과</th>
                <th>사용방법</th>
                <th>제품 사진</th>
            </tr>
            </thead>
            <tbody>
            {% for item in data %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.entpName }}</td>
                <td>{{ item.efcyQesitm }}</td>
                <td>{{ item.useMethodQesitm }}</td>
                <td><img src="{{ item.itemImage or url_for('static', filename='default_image.png') }}" width="200"
                         height="200"
                         alt="제품 이미지"></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <p>페이지: {{ current_page }} / {{ total_pages }}</p>
        <div>
            {% set start_page = ((current_page - 1) // 10) * 10 + 1 %}
            {% set end_page = start_page + 9 %}
            {% if end_page > total_pages %}
            {% set end_page = total_pages %}
            {% endif %}

            {% if current_page > 10 %}
            <a href="{{ url_for('yak.search', page=start_page-10, search_query1=request.args.get('search_query1', ''), numOfRows=numOfRows) }}">이전</a>
            {% endif %}

            {% for page in range(start_page, end_page + 1) %}
            {% if page == current_page %}
            <strong>{{ page }}</strong>
            {% else %}
            <a href="{{ url_for('yak.search', page=page, search_query1=request.args.get('search_query1', ''), numOfRows=numOfRows) }}">{{
                page }}</a>
            {% endif %}
            {% endfor %}

            {% if end_page < total_pages %}
            <a href="{{ url_for('yak.search', page=start_page+10, search_query1=request.args.get('search_query1', ''), numOfRows=numOfRows) }}">다음</a>
            {% endif %}
        </div>

    </div>

    {% else %}
    <p>검색 결과가 없습니다.</p>
    {% endif %}
</div>
{% endblock %}