dieasemain/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

import functools

from dieasemain import db
from dieasemain.forms import UserCreateForm, UserLoginForm
from dieasemain.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.before_app_request #이 어노테이션은 라우팅 함수보다 먼저 실행됨
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    # 여기서 테이블 값과 비교해서 중복여부를 검사함
    if request.method == 'POST' and form.validate_on_submit():
        print(form)
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data): #자체 메소드, 내장 함수 , 라이브러리에 저장된 것
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

dieasemain/views/game_views.py
from flask import Blueprint, url_for, render_template

from werkzeug.utils import redirect


bp = Blueprint('game', __name__, url_prefix='/')


@bp.route('/game/')
def list():
    return render_template('game/list.html') # game/list/ 가져오는 것

dieasemain/views/timer_views.py
from flask import Blueprint, url_for, render_template

from werkzeug.utils import redirect


bp = Blueprint('time', __name__, url_prefix='/')


@bp.route('/time/')
def timer():
    return render_template('time/timer.html') # game/list/ 가져오는 것

dieasemain/views/yak_views.py
import requests
import xml.etree.ElementTree as ET
from flask import Blueprint, url_for, request, render_template, g
from flask import Blueprint, url_for, render_template, abort
from werkzeug.utils import redirect

bp = Blueprint('yak', __name__, url_prefix='/')
totalCount = 0


@bp.route('/yak', methods=['GET', 'POST'])
def list():
    if request.method == 'POST':
        # 검색 폼이 제출되었을 때의 처리
        search_query = request.form['search_query1']
        print(search_query, "=================================")

    else:
        data1 = []
        url = 'http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList'
        pageNo = int(request.args.get('page', 1))
        numOfRows = int(request.args.get('numOfRows', 10))  # 한 페이지에 보여질 항목 수
        params = {
            'serviceKey': 'VQjISU0hGRUuuYzKzUZimCJgNkWsFFAr0VpkfbEIVawBMPCw0FI9aXf0bJ2v1zuDQe45Kupb0ajUCJwjGNQ2cA==',
            'pageNo': pageNo, 'numOfRows': numOfRows, 'entpName': '', 'itemName': '', 'itemSeq': '', 'efcyQesitm': '',
            'useMethodQesitm': '', 'atpnWarnQesitm': '', 'atpnQesitm': '', 'intrcQesitm': '', 'seQesitm': '',
            'depositMethodQesitm': '', 'openDe': '', 'updateDe': '', 'type': 'xml'}
        response = requests.get(url, params=params)

        print(response.status_code)

        if response.status_code == 200:
            # XML 데이터를 파싱합니다
            root = ET.fromstring(response.content)

            try:
                for item in root.findall('.//item'):  # 'item' 태그를 가진 모든 요소를 찾습니다
                    entry = {
                        'itemName': item.find('itemName').text,
                        'itemSeq': item.find('itemSeq').text,  # 상세 정보를 위해 itemSeq를 저장
                        'entpName': item.find('entpName').text,
                        'efcyQesitm': item.find('efcyQesitm').text,
                        'useMethodQesitm': item.find('useMethodQesitm').text,
                        'atpnWarnQesitm': item.find('atpnWarnQesitm').text,
                        'atpnQesitm': item.find('atpnQesitm').text,
                        'intrcQesitm': item.find('intrcQesitm').text,
                        'seQesitm': item.find('seQesitm').text,
                        'depositMethodQesitm': item.find('depositMethodQesitm').text
                    }
                    data1.append(entry)
                totalCount = int(root.find('.//totalCount').text)
                for item in root.findall('.//response'):  # 'item' 태그를 가진 모든 요소를 찾습니다
                    entry1 = {
                        'pageNo': item.find('pageNo').text
                    }
                    data1.append(entry1)

            except ET.ParseError as e:
                print(f"XML 파싱 오류: {e}")
                data1 = []

            total_pages = (totalCount + numOfRows - 1) // numOfRows

    return render_template('yak/list.html', data=data1, totalCount=totalCount, total_pages=total_pages,
                           current_page=pageNo, numOfRows=numOfRows)


# 약품의 세부정보 확인
@bp.route('/yak/<int:itemSeq><itemName>')
def detail(itemSeq, itemName):
    data1 = []
    url = 'http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList'
    pageNo = int(request.args.get('page', 1))
    numOfRows = int(request.args.get('numOfRows', 10))  # 한 페이지에 보여질 항목 수
    params = {
        'serviceKey': 'VQjISU0hGRUuuYzKzUZimCJgNkWsFFAr0VpkfbEIVawBMPCw0FI9aXf0bJ2v1zuDQe45Kupb0ajUCJwjGNQ2cA==',
        'pageNo': pageNo, 'numOfRows': numOfRows, 'entpName': '', 'itemName': itemName, 'itemSeq': '', 'efcyQesitm': '',
        'useMethodQesitm': '', 'atpnWarnQesitm': '', 'atpnQesitm': '', 'intrcQesitm': '', 'seQesitm': '',
        'depositMethodQesitm': '', 'openDe': '', 'updateDe': '', 'type': 'xml'}
    response = requests.get(url, params=params)

    root = ET.fromstring(response.content)

    detail_data = {}
    item = root.find('.//item')
    if item is not None:
        detail_data = {
            'name': item.find('itemName').text,
            'entpName': item.find('entpName').text,
            'efcyQesitm': item.find('efcyQesitm').text,
            'useMethodQesitm': item.find('useMethodQesitm').text,
            'atpnWarnQesitm': item.find('atpnWarnQesitm').text,
            'atpnQesitm': item.find('atpnQesitm').text,
            'intrcQesitm': item.find('intrcQesitm').text,
            'seQesitm': item.find('seQesitm').text,
            'depositMethodQesitm': item.find('depositMethodQesitm').text,
            'itemImage': item.find('itemImage').text
        }
        data1.append(detail_data)
    else:
        print("아이템을 찾을 수 없습니다.")
        abort(404, description="Item not found.")

    return render_template('yak/detail.html', detail_data=detail_data)


# # 약품의 세부정보 확인
# @bp.route('/yak/search')
# def search():
#     detail_data = {}
#     data1 = []
#     # GET 요청으로 받은 검색어 처리
#     search_query = request.args.get('search_query1')
#     print(search_query)
#
#     pageNo = int(request.args.get('page', 1))
#     numOfRows = int(request.args.get('numOfRows', 100))  # 한 페이지에 보여질 항목 수
#     print(search_query)
#     efcyQesitm = search_query
#     # API를 호출하여 검색 결과를 가져옵니다.
#     # 가져온 결과를 템플릿에 전달하여 보여줍니다.
#     url = 'http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList'
#     pageNo = int(request.args.get('page', 1))
#     params = {
#         'serviceKey': 'VQjISU0hGRUuuYzKzUZimCJgNkWsFFAr0VpkfbEIVawBMPCw0FI9aXf0bJ2v1zuDQe45Kupb0ajUCJwjGNQ2cA==',
#         'pageNo': pageNo, 'numOfRows': numOfRows, 'entpName': '', 'itemName': '', 'itemSeq': '', 'efcyQesitm': efcyQesitm,
#         'useMethodQesitm': '', 'atpnWarnQesitm': '', 'atpnQesitm': '', 'intrcQesitm': '', 'seQesitm': '',
#         'depositMethodQesitm': '', 'openDe': '', 'updateDe': '', 'type': 'xml'}
#     response = requests.get(url, params=params)
#
#     root = ET.fromstring(response.content)
#
#     item = root.find('.//item')
#     if item is not None:
#         print(search_query, "=============================================================")
#         detail_data = {
#             'name': item.find('itemName').text,
#             'entpName': item.find('entpName').text,
#             'efcyQesitm': item.find('efcyQesitm').text,
#             'useMethodQesitm': item.find('useMethodQesitm').text,
#             'atpnWarnQesitm': item.find('atpnWarnQesitm').text,
#             'atpnQesitm': item.find('atpnQesitm').text,
#             'intrcQesitm': item.find('intrcQesitm').text,
#             'seQesitm': item.find('seQesitm').text,
#             'depositMethodQesitm': item.find('depositMethodQesitm').text,
#             'itemImage': item.find('itemImage').text
#         }
#         data1.append(detail_data)
#     else:
#         print("아이템을 찾을 수 없습니다.")
#         abort(404, description="Item not found.")
#
#     totalCount = int(root.find('.//totalCount').text)
#     for item in root.findall('.//response'):  # 'item' 태그를 가진 모든 요소를 찾습니다
#         entry1 = {
#             'pageNo': item.find('pageNo').text
#         }
#         data1.append(entry1)
#
#     data1 = []
#
#     total_pages = (totalCount + numOfRows - 1) // numOfRows
#
#     return render_template('yak/search_form.html', detail_data=detail_data,totalCount=totalCount, total_pages=total_pages,
#                            current_page=pageNo, numOfRows=numOfRows)
#


@bp.route('/yak/search')
def search():
    search_query = request.args.get('search_query1', '')
    pageNo = int(request.args.get('page', 1))
    numOfRows = int(request.args.get('numOfRows', 10))

    url = 'http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList'
    params = {
        'serviceKey': 'VQjISU0hGRUuuYzKzUZimCJgNkWsFFAr0VpkfbEIVawBMPCw0FI9aXf0bJ2v1zuDQe45Kupb0ajUCJwjGNQ2cA==',
        'pageNo': pageNo, 'numOfRows': numOfRows, 'entpName': '', 'itemName': '', 'itemSeq': '',
        'efcyQesitm': search_query,  # 검색어를 efcyQesitm에 포함
        'useMethodQesitm': '', 'atpnWarnQesitm': '', 'atpnQesitm': '', 'intrcQesitm': '', 'seQesitm': '',
        'depositMethodQesitm': '', 'openDe': '', 'updateDe': '', 'type': 'xml'}

    response = requests.get(url, params=params)

    data1 = []
    totalCount = 0
    total_pages = 0

    if response.status_code == 200:
        root = ET.fromstring(response.content)
        items = root.findall('.//item')

        if items:
            for item in items:
                efcyQesitm_text = item.find('efcyQesitm').text if item.find('efcyQesitm') is not None else ''
                if search_query in efcyQesitm_text:
                    detail_data = {
                        'name': item.find('itemName').text if item.find('itemName') is not None else 'N/A',
                        'entpName': item.find('entpName').text if item.find('entpName') is not None else 'N/A',
                        'efcyQesitm': item.find('efcyQesitm').text if item.find('efcyQesitm') is not None else 'N/A',
                        'useMethodQesitm': item.find('useMethodQesitm').text if item.find('useMethodQesitm') is not None else 'N/A',
                        'atpnWarnQesitm': item.find('atpnWarnQesitm').text if item.find('atpnWarnQesitm') is not None else 'N/A',
                        'itemImage': item.find('itemImage').text if item.find('itemImage') is not None else 'N/A'
                    }
                    data1.append(detail_data)

            totalCount = int(root.find('.//totalCount').text)
            total_pages = (totalCount + numOfRows - 1) // numOfRows
        else:
            abort(404, description="Item not found.")
    else:
        abort(response.status_code, description="API request failed.")

    return render_template('yak/search_form.html', search_query=search_query, data=data1, totalCount=totalCount, total_pages=total_pages,
                           current_page=pageNo, numOfRows=numOfRows)

dieasemain/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--상문이가 만든 CSS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css.css') }}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <!-- 아이콘 그림-->
    <link rel="icon" href="{{ url_for('static', filename='yak.png') }}"><link>
    <title>I'M SICK</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->

{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

dieasemain/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

dieasemain/templates/index.html
{% extends 'base.html' %}
{% block content %}


<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">


<div class="wrap">
    <div class="intro_bg">
        <img src="{{ url_for('static', filename='2.jpg') }}" alt="Intro Image">
    </div>

    <ul class="amount">
        <li>
            <div>
                <button type="button" onclick="location.href='https://www.nhis.or.kr/nhis/index.do'" style="width: 70%; height: 100%" >국민건강보험</button>
            </div>
        </li>
        <li>
            <div>
                <button type="button" onclick="location.href='https://www.kdca.go.kr/'" style="width: 70%; height: 100%" >질병관리청</button>
            </div>
        </li>
        <li>
            <div>
                <button type="button" onclick="location.href='https://www.bloodinfo.net/knrcbs/main.do'" style="width: 70%; height: 100%" >대한적십자사</button>
            </div>
        </li>
        <li>
            <div>
                <button type="button" onclick="location.href='https://www.koiha.or.kr/web/kr/index.do'" style="width: 70%; height: 100%" >의료기관평가인증원</button>
            </div>
        </li>
    </ul>

    <div class="main_text0">
        <h1>ABOUT</h1>
        <div class="contents1">건강 걱정을 함께 나누면서 당신을 응원할게요. 언제든지 제게 말해주세요</div>

        <ul class="icons">
            <li>
                <div class="icon_img">
                    <img src="{{ url_for('static', filename='5.jpg') }}">
                </div>
                <div class="contents1_bold">질환 확인</div>
                <div class="contents1">
                    증상 입력을 통한 질환 정보 제공
                </div>
            </li>
            <li>
                <div class="icon_img">
                    <img src="{{ url_for('static', filename='4.jpg') }}">
                </div>
                <div class="contents1_bold">의약품 파악</div>
                <div class="contents1">
                    효능·주의사항·부작용·보관법
                </div>
            </li>
            <li>
                <div class="icon_img">
                    <img src="{{ url_for('static', filename='7.jpg') }}">
                </div>
                <div class="contents1_bold">헬스케어</div>
                <div class="contents1">
                    운동을 통한 삶의 질 향상
                </div>
            </li>
        </ul>


    </div>

</div>

{% endblock %}

dieasemain/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">I'M SICK</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
             {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('predict.main') }}">질병진단</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('yak.list') }}">약품추천</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('time.timer') }}">복약알림</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('hospital.hospital') }}">병원찾기</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('health.list') }}">홈트레이닝</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link" href="{{ url_for('game.list') }}">두뇌발달</a>
                </li>
                <li class="nav-item">
            <a class="nav-link" href="{{ url_for('question._list') }}">자유게시판</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>